#' For setting the knitr hooks
#'
#' This should *not* be called directly by the user.
#'
#' See zzz.R for where knitr_hooks$set() is actually invoked
devoirs_knitr_hooks <- function(x) {
  json_mc <- jsonlite::toJSON(devoirs_state$registered_mc, auto_unbox = TRUE)
  json_text <- jsonlite::toJSON(devoirs_state$registered_text, auto_unbox = TRUE)
  json_word <- jsonlite::toJSON(devoirs_state$registered_words, auto_unbox = TRUE)
  json_num <- jsonlite::toJSON(devoirs_state$registered_nums, auto_unbox = TRUE)
  json_set <- jsonlite::toJSON(devoirs_state$registered_sets, auto_unbox = TRUE)
  source_qmd_name <- devoirs_state$source_file

  js_builder <- c(
    "<script>",
    paste0("var devoirsMcMeta = ", json_mc, ";"),
    paste0("var devoirsTextLabels = ", json_text, ";"),
    paste0("var devoirsWordMeta = ", json_word, ";"),
    paste0("var devoirsNumMeta = ", json_num, ";"),
    paste0("var devoirsSetMeta = ", json_set, ";"),
    paste0("var devoirsSourceFile = \"", source_qmd_name, "\";"),
    "",
    "window.addEventListener('DOMContentLoaded', function() {",
    "  for (var chunkLabel in devoirsMcMeta) {",
    "    var items = devoirsMcMeta[chunkLabel];",
    "    items.forEach(function(item) {",
    "      var form = document.getElementById('form_' + item.itemId);",
    "      if (!form) return;",
    "      var inputs = form.querySelectorAll('input');",
    "      inputs.forEach(function(input) {",
    "        var savedValue = localStorage.getItem('devoirs_mc_' + chunkLabel + '_' + input.value);",
    "        if (savedValue === 'true') {",
    "          input.checked = true;",
    "          input.dispatchEvent(new Event('change'));",
    "        }",
    "      });",
    "    });",
    "  }",
    "  for (var label in devoirsTextLabels) {",
    "    var inputEl = document.getElementById('txt_input_' + label);",
    "    var savedText = localStorage.getItem('devoirs_text_' + label);",
    "    if (inputEl && savedText) inputEl.value = savedText;",
    "  }",
    "  for (var wordId in devoirsWordMeta) {",
    "    var inputEl = document.getElementById('w_input_' + wordId);",
    "    var savedWord = localStorage.getItem('devoirs_word_' + wordId);",
    "    if (inputEl && savedWord) {",
    "      inputEl.value = savedWord;",
    "      inputEl.dispatchEvent(new Event('input'));",
    "    }",
    "  }",
    "  for (var numId in devoirsNumMeta) {",
    "    var inputEl = document.getElementById('n_input_' + numId);",
    "    var savedNum = localStorage.getItem('devoirs_num_' + numId);",
    "    if (inputEl && savedNum) {",
    "      inputEl.value = savedNum;",
    "      inputEl.dispatchEvent(new Event('input'));",
    "    }",
    "  }",
    "  // Hydrate dropdown selections from localStorage",
    "  for (var setId in devoirsSetMeta) {",
    "    var inputEl = document.getElementById('s_input_' + setId);",
    "    var savedSet = localStorage.getItem('devoirs_set_' + setId);",
    "    if (inputEl && savedSet) {",
    "      inputEl.value = savedSet;",
    "      inputEl.dispatchEvent(new Event('change'));",
    "    }",
    "  }",
    "});",
    "",
    "function clearDevoirsCache() {",
    "  if (!confirm('Are you sure you want to clear your saved answers?')) return;",
    "  for (var chunkLabel in devoirsMcMeta) {",
    "    var items = devoirsMcMeta[chunkLabel];",
    "    items.forEach(function(item) {",
    "      var form = document.getElementById('form_' + item.itemId);",
    "      if (!form) return;",
    "      var inputs = form.querySelectorAll('input');",
    "      inputs.forEach(function(input) {",
    "        input.checked = false;",
    "        localStorage.removeItem('devoirs_mc_' + chunkLabel + '_' + input.value);",
    "      });",
    "      var fb = form.previousElementSibling ? form.previousElementSibling.querySelector('div') : null;",
    "      if (fb) fb.innerHTML = '';",
    "    });",
    "  }",
    "  for (var label in devoirsTextLabels) {",
    "    var inputEl = document.getElementById('txt_input_' + label);",
    "    if (inputEl) inputEl.value = '';",
    "    localStorage.removeItem('devoirs_text_' + label);",
    "  }",
    "  for (var wordId in devoirsWordMeta) {",
    "    var inputEl = document.getElementById('w_input_' + wordId);",
    "    if (inputEl) { inputEl.value = ''; inputEl.style.backgroundColor = ''; inputEl.style.borderColor = '#ccc'; }",
    "    localStorage.removeItem('devoirs_word_' + wordId);",
    "  }",
    "  for (var numId in devoirsNumMeta) {",
    "    var inputEl = document.getElementById('n_input_' + numId);",
    "    if (inputEl) { inputEl.value = ''; inputEl.style.backgroundColor = ''; inputEl.style.borderColor = '#ccc'; }",
    "    localStorage.removeItem('devoirs_num_' + numId);",
    "  }",
    "  for (var setId in devoirsSetMeta) {",
    "    var inputEl = document.getElementById('s_input_' + setId);",
    "    if (inputEl) { inputEl.value = ''; var iconSpan = document.getElementById('s_fb_' + setId); if (iconSpan) iconSpan.innerHTML = ''; }",
    "    localStorage.removeItem('devoirs_set_' + setId);",
    "  }",
    "}",
    "",
    "function generate3DigitSuffix(isCorrect) {",
    "  while(true) {",
    "    var num = Math.floor(Math.random() * 900) + 100;",
    "    if (isCorrect && num % 7 === 0) return num;",
    "    if (!isCorrect && num % 7 !== 0) return num;",
    "  }",
    "}",
    "function processDevoirsSubmission() {",
    "  var yamlLines = [",
    "    'document: \"' + devoirsSourceFile + '\"',",
    "    'responses:'",
    "  ];",
    "  var currentTimestamp = new Date().toISOString();",
    "  for (var chunkLabel in devoirsMcMeta) {",
    "    yamlLines.push('  ' + chunkLabel + ':');",
    "    var itemsList = devoirsMcMeta[chunkLabel];",
    "    var chosenIdsWithSuffixes = [];",
    "    var totalCorrectAnswers = 0;",
    "    var maxPoints = 0;",
    "    itemsList.forEach(function(itemMeta) {",
    "      totalCorrectAnswers += itemMeta.totalCorrect;",
    "      maxPoints += itemMeta.points;",
    "      var form = document.getElementById('form_' + itemMeta.itemId);",
    "      if (!form) return;",
    "      var checkedInputs = Array.from(form.querySelectorAll('input:checked'));",
    "      checkedInputs.forEach(function(input) {",
    "        var attrVal = input.getAttribute('data-correct') || 'false';",
    "        var isChoiceCorrect = attrVal.toLowerCase() === 'true';",
    "        var suffix = generate3DigitSuffix(isChoiceCorrect);",
    "        chosenIdsWithSuffixes.push('\"' + input.value + '-' + suffix + '\"');",
    "      });",
    "    });",
    "    yamlLines.push('      ids: [' + chosenIdsWithSuffixes.join(', ') + ']');",
    "    yamlLines.push('      multiplicity: ' + totalCorrectAnswers);",
    "    yamlLines.push('      max_points: ' + maxPoints);",
    "  }",
    "  for (var label in devoirsTextLabels) {",
    "    var inputEl = document.getElementById('txt_input_' + label);",
    "    var userValue = inputEl ? inputEl.value : '';",
    "    yamlLines.push('  ' + label + ':');",
    "    var escapedValue = userValue.replace(/\"/g, '\\\\\"').replace(/\\n/g, '\\\\n');",
    "    yamlLines.push('      contents: \"' + escapedValue + '\"');",
    "    yamlLines.push('      max_points: ' + devoirsTextLabels[label].points);",
    "  }",
    "  for (var wordId in devoirsWordMeta) {",
    "    var inputEl = document.getElementById('w_input_' + wordId);",
    "    var userValue = inputEl ? inputEl.value : '';",
    "    var meta = devoirsWordMeta[wordId];",
    "    yamlLines.push('  ' + wordId + ':');",
    "    var escapedValue = userValue.replace(/\"/g, '\\\\\"');",
    "    yamlLines.push('      contents: \"' + escapedValue + '\"');",
    "    yamlLines.push('      true_answer: \"' + meta.trueAnswer + '\"');",
    "    yamlLines.push('      max_points: ' + meta.points);",
    "  }",
    "  for (var numId in devoirsNumMeta) {",
    "    var inputEl = document.getElementById('n_input_' + numId);",
    "    var userValue = inputEl ? inputEl.value : '';",
    "    var meta = devoirsNumMeta[numId];",
    "    yamlLines.push('  ' + numId + ':');",
    "    yamlLines.push('      contents: \"' + userValue.trim() + '\"');",
    "    yamlLines.push('      true_answer: ' + meta.trueAnswer);",
    "    yamlLines.push('      interval: ' + meta.interval);",
    "    yamlLines.push('      max_points: ' + meta.points);",
    "  }",
    "  // MODULE E: Process dropdown menus dynamically",
    "  for (var setId in devoirsSetMeta) {",
    "    var inputEl = document.getElementById('s_input_' + setId);",
    "    var userValue = inputEl ? inputEl.value : '';",
    "    var meta = devoirsSetMeta[setId];",
    "    yamlLines.push('  ' + setId + ':');",
    "    var escapedValue = userValue.replace(/\"/g, '\\\\\"');",
    "    yamlLines.push('      contents: \"' + escapedValue + '\"');",
    "    yamlLines.push('      true_answer: \"' + meta.correct + '\"');",
    "    yamlLines.push('      max_points: ' + meta.points);",
    "  }",
    "  yamlLines.push('timestamp: \"' + currentTimestamp + '\"');",
    "  var completeYamlText = yamlLines.join('\\n');",
    "  navigator.clipboard.writeText(completeYamlText).catch(function(err) {",
    "    alert('Clipboard extraction crash: ' + err);",
    "  });",
    "}",
    "</script>"
  )
  js_block_string <- paste(js_builder, collapse = "\n")
  x <- sub("<!-- EXPORT_SCRIPT_PLACEHOLDER -->", js_block_string, x, fixed = TRUE)
  return(x)
}
